# ============================================================
# Atlantic Forest pollination project
#
# Purpose
# - Read the canonical inputs generated by 01_prepare_pam_grid_inputs.R
#   and by the Google Earth Engine MapBiomas step.
# - Calculate municipal pollination demand, EV, APEV and RV.
# - Redistribute municipal values dasymetrically to 5-km grid cells.
# - Estimate potential habitat supply, risk and demand-supply mismatch.
# - Identify critical hotspots, concentration patterns, crop drivers,
#   correlations and article tables.
#
# Important
# - Run this script from the project root, i.e. the folder that contains
#   data_raw/ and output_mata_atlantica/.
# ============================================================

# ------------------------------------------------------------
# 0) Packages
# ------------------------------------------------------------
required_packages <- c(
  "sf", "dplyr", "readr", "tidyr", "stringr", "readxl", "tibble", "janitor"
)

missing_packages <- setdiff(required_packages, rownames(installed.packages()))
if (length(missing_packages) > 0) {
  stop(
    "Please install the missing packages before running this script: ",
    paste(missing_packages, collapse = ", ")
  )
}

invisible(lapply(required_packages, library, character.only = TRUE))

# ------------------------------------------------------------
# 1) Paths and input files
# ------------------------------------------------------------
raw_dir <- "data_raw"
output_dir <- "output_mata_atlantica"

tab_dir <- file.path(output_dir, "tables")

# Figures are generated by the next script.
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
dir.create(tab_dir, showWarnings = FALSE, recursive = TRUE)

# Canonical raw input produced by the GEE MapBiomas step.
file_mapbiomas_grid <- file.path(
  raw_dir,
  "mapbiomas_grid_atlantic_forest_2024.csv"
)

# Canonical outputs produced by 01_prepare_pam_grid_inputs.R.
file_grid <- file.path(
  output_dir,
  "atlantic_forest_grid_5km.gpkg"
)

file_pam_dependence <- file.path(
  output_dir,
  "pam_atlantic_forest_long_2020_2024_dependence.csv"
)

# Canonical raw reference table.
file_dependence_reference <- file.path(
  raw_dir,
  "pollination_dependence_reference.xlsx"
)

required_files <- c(
  file_mapbiomas_grid,
  file_grid,
  file_pam_dependence,
  file_dependence_reference
)

missing_files <- required_files[!file.exists(required_files)]
if (length(missing_files) > 0) {
  stop(
    "The following required files were not found. Check file names and run order:\n",
    paste(missing_files, collapse = "\n")
  )
}

# ------------------------------------------------------------
# 2) Global definitions
# ------------------------------------------------------------

main_dependence_levels <- c("essential", "high", "modest")

# BRL per 1 USD. Replaced with official annual mean PTAX/BCB values.
exchange_rates <- tibble::tribble(
  ~year, ~brl_per_usd,
  2020, 5.16,
  2021, 5.40,
  2022, 5.16,
  2023, 4.99,
  2024, 5.39
)

# ------------------------------------------------------------
# 3) Read input data
# ------------------------------------------------------------

# MapBiomas/GEE output keeps original Portuguese column names.
# They are converted to English internal names here.
grid_municipality_area <- readr::read_csv(file_mapbiomas_grid, show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  dplyr::transmute(
    grid_id = as.character(id_grid),
    municipality_code = stringr::str_extract(as.character(codigo_municipio), "\\d{7}"),
    municipality_name = as.character(municipio),
    state_code = as.character(code_state),
    state_abbrev = as.character(abbrev_state),
    intersection_area_ha = as.numeric(area_inter_ha),
    agricultural_area_grid_municipality_ha = as.numeric(area_agri_gym_ha),
    native_area_grid_municipality_ha = as.numeric(area_nativa_gym_ha)
  )

grid <- sf::st_read(file_grid, quiet = TRUE) %>%
  janitor::clean_names()

if ("grid_id" %in% names(grid)) {
  grid <- grid %>%
    dplyr::mutate(grid_id = as.character(grid_id))
} else if ("id_grid" %in% names(grid)) {
  grid <- grid %>%
    dplyr::mutate(grid_id = as.character(id_grid)) %>%
    dplyr::select(-dplyr::any_of("id_grid"))
} else {
  stop("The grid layer must contain either 'grid_id' or 'id_grid'.")
}

# This file was written by 01_prepare_pam_grid_inputs.R with English column names.
pam_records <- readr::read_csv(file_pam_dependence, show_col_types = FALSE) %>%
  janitor::clean_names() %>%
  dplyr::transmute(
    year = as.integer(year),
    crop_type = as.character(crop_type),
    municipality_code = stringr::str_extract(as.character(municipality_code), "\\d{7}"),
    municipality_name = as.character(municipality_name),
    crop_code = as.character(crop_code),
    crop_name = as.character(crop_name),
    variable_code = as.character(variable_code),
    variable_name = as.character(variable_name),
    value = as.numeric(value)
  )

dependence_ref_raw <- readxl::read_excel(file_dependence_reference)

# ------------------------------------------------------------
# 4) Input field checks
# ------------------------------------------------------------

required_grid_municipality_columns <- c(
  "grid_id", "municipality_code", "municipality_name", "state_code", "state_abbrev",
  "intersection_area_ha", "agricultural_area_grid_municipality_ha",
  "native_area_grid_municipality_ha"
)

missing_grid_municipality_columns <- setdiff(
  required_grid_municipality_columns,
  names(grid_municipality_area)
)

if (length(missing_grid_municipality_columns) > 0) {
  stop(
    "Missing columns in grid_municipality_area: ",
    paste(missing_grid_municipality_columns, collapse = ", ")
  )
}

if (any(is.na(grid$grid_id))) {
  stop("The grid layer must contain a valid grid_id/id_grid field.")
}

# ============================================================
# PART 1 — UPDATED CROP POLLINATION DEPENDENCE
# ============================================================

# ------------------------------------------------------------
# 5) Check duplicated crop codes before removing duplicates
# ------------------------------------------------------------

duplicated_crop_codes_reference <- dependence_ref_raw %>%
  dplyr::transmute(
    crop_code = as.character(`IBGE crop code`)
  ) %>%
  dplyr::count(crop_code) %>%
  dplyr::filter(n > 1)

if (nrow(duplicated_crop_codes_reference) > 0) {
  print(duplicated_crop_codes_reference)
  stop("There are duplicated crop_code values in pollination_dependence_reference.xlsx.")
}

# ------------------------------------------------------------
# 6) Standardize the new pollination dependence table
# ------------------------------------------------------------

dependence_ref <- dependence_ref_raw %>%
  janitor::clean_names() %>%
  dplyr::transmute(
    crop_code = as.character(ibge_crop_code),
    crop_name_english = as.character(crop_name_english),
    pam_crop_name_reference = as.character(original_pam_crop_name),
    pollination_dependence_original = as.character(pollination_dependence),
    pollination_dependence = pollination_dependence_original %>%
      stringr::str_to_lower() %>%
      stringr::str_squish(),
    dependence_score = as.numeric(
      stringr::str_replace(as.character(dependence_score), ",", ".")
    ),
    classification_reference = as.character(reference)
  ) %>%
  dplyr::mutate(
    pollination_dependence = dplyr::case_when(
      pollination_dependence == "essential" ~ "essential",
      pollination_dependence == "high" ~ "high",
      pollination_dependence == "modest" ~ "modest",
      pollination_dependence == "little" ~ "little",
      pollination_dependence == "no increase" ~ "no increase",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::distinct(crop_code, .keep_all = TRUE)

# ------------------------------------------------------------
# 7) Quality checks for dependence table
# ------------------------------------------------------------

dependence_class_audit <- dependence_ref %>%
  count(
    pollination_dependence_original,
    pollination_dependence,
    dependence_score,
    sort = TRUE
  )

print(dependence_class_audit)

dependence_problem_records <- dependence_ref %>%
  filter(
    is.na(pollination_dependence) |
      is.na(dependence_score)
  )

if (nrow(dependence_problem_records) > 0) {
  print(dependence_problem_records)
  stop("Some rows in pollination_dependence_reference.xlsx have missing dependence class or score.")
}

# ------------------------------------------------------------
# 8) Standardize PAM and replace old dependence classification
# ------------------------------------------------------------
# Important:
# - The new dependence table replaces previous dependence columns.
# - Crops not found in dependence_ref remain with NA dependence and NA score.
# - Undefined crops are excluded from PD and APEV calculations.
# - Undefined crops remain in EV, because EV is total agricultural production
#   value based on all PAM crops with production value records.

pam <- pam_records %>%
  dplyr::mutate(
    year = as.integer(year),
    municipality_code = as.character(municipality_code),
    crop_code = as.character(crop_code),
    value = as.numeric(value),
    variable_name_clean = variable_name %>%
      stringr::str_to_lower() %>%
      iconv(from = "UTF-8", to = "ASCII//TRANSLIT") %>%
      stringr::str_replace_all("[^[:alnum:]]+", " ") %>%
      stringr::str_squish()
  ) %>%
  dplyr::filter(
    year %in% 2020:2024,
    crop_code != "0"
  ) %>%
  dplyr::select(
    -dplyr::any_of(c(
      "pollination_dependence",
      "dependence_score",
      "classification_reference",
      "crop_name_english",
      "pam_crop_name_reference",
      "pollination_dependence_original"
    ))
  ) %>%
  dplyr::left_join(dependence_ref, by = "crop_code") %>%
  dplyr::mutate(
    has_defined_dependence = !is.na(pollination_dependence),
    pollination_dependence = factor(
      pollination_dependence,
      levels = c(
        "essential",
        "high",
        "modest",
        "little",
        "no increase"
      )
    ),
    is_main_pollination_crop =
      as.character(pollination_dependence) %in% main_dependence_levels
  )

# ------------------------------------------------------------
# 9) Check PAM crops without reference in the new table
# ------------------------------------------------------------

pam_crops_missing_reference <- pam_records %>%
  mutate(crop_code = as.character(crop_code)) %>%
  filter(crop_code != "0") %>%
  distinct(crop_code, crop_name) %>%
  anti_join(dependence_ref, by = "crop_code") %>%
  arrange(crop_name)

# ------------------------------------------------------------
# 10) Check final crop dependence used in PAM
# ------------------------------------------------------------

pam_dependence_audit <- pam %>%
  distinct(
    crop_code,
    crop_name,
    pollination_dependence,
    dependence_score,
    classification_reference,
    has_defined_dependence,
    is_main_pollination_crop
  ) %>%
  arrange(desc(dependence_score), crop_name)

print(
  pam_dependence_audit %>%
    count(
      pollination_dependence,
      dependence_score,
      has_defined_dependence,
      is_main_pollination_crop
    )
)

# ============================================================
# PART A — MUNICIPAL POLLINATION DEMAND
# ============================================================

# ------------------------------------------------------------
# 11) Select production quantity
# ------------------------------------------------------------

pam_quantity_all <- pam %>%
  filter(variable_name_clean == "quantidade produzida")

# Main analysis includes only essential, high and modest dependence.
pam_quantity_main <- pam_quantity_all %>%
  filter(is_main_pollination_crop)

# ------------------------------------------------------------
# 12) Annual municipal pollination demand
# PD_imy = Q_imy * D_i
# PD_my  = sum_i(Q_imy * D_i)
# ------------------------------------------------------------

municipal_demand_year <- pam_quantity_main %>%
  mutate(
    production_quantity = value,
    pollination_demand_crop = production_quantity * dependence_score
  ) %>%
  group_by(year, municipality_code, municipality_name) %>%
  summarise(
    production_main_total = sum(production_quantity, na.rm = TRUE),
    pollination_demand = sum(pollination_demand_crop, na.rm = TRUE),
    n_main_pollination_crops =
      n_distinct(crop_code[production_quantity > 0]),
    .groups = "drop"
  )

# ------------------------------------------------------------
# 13) Mean municipal demand, 2020–2024
# ------------------------------------------------------------

municipal_demand_mean <- municipal_demand_year %>%
  group_by(municipality_code, municipality_name) %>%
  summarise(
    production_main_total_mean_2020_2024 =
      mean(production_main_total, na.rm = TRUE),
    PD_mean_2020_2024 =
      mean(pollination_demand, na.rm = TRUE),
    n_main_crops_mean_2020_2024 =
      mean(n_main_pollination_crops, na.rm = TRUE),
    .groups = "drop"
  )

# ============================================================
# PART B — ECONOMIC VALUE OF AGRICULTURAL PRODUCTION
# ============================================================

# ------------------------------------------------------------
# 14) Select production value
# ------------------------------------------------------------
# EV is total agricultural production value and includes all PAM crops.
# APEV is calculated only for the main pollinator-dependent crop set:
# essential, high and modest.

pam_value_all <- pam %>%
  filter(variable_name == "Valor da produção")

# ------------------------------------------------------------
# 15) Annual EV, APEV and RV in thousand BRL
# EV_my   = sum_i(V_imy), using all crops
# APEV_my = sum_i(V_imy * D_i), using only main dependence crops
# RV_my   = APEV_my / EV_my * 100
# ------------------------------------------------------------

municipal_economic_year_brl <- pam_value_all %>%
  mutate(
    value_brl_thousand = value,
    pollination_value_brl_thousand = ifelse(
      is_main_pollination_crop,
      value_brl_thousand * dependence_score,
      0
    )
  ) %>%
  group_by(year, municipality_code, municipality_name) %>%
  summarise(
    EV_brl_thousand =
      sum(value_brl_thousand, na.rm = TRUE),
    APEV_brl_thousand =
      sum(pollination_value_brl_thousand, na.rm = TRUE),
    n_crops_total_economic =
      n_distinct(crop_code[value_brl_thousand > 0]),
    n_main_pollination_crops_economic =
      n_distinct(
        crop_code[
          is_main_pollination_crop &
            value_brl_thousand > 0
        ]
      ),
    .groups = "drop"
  ) %>%
  mutate(
    RV_percent = ifelse(
      EV_brl_thousand > 0,
      APEV_brl_thousand / EV_brl_thousand * 100,
      NA_real_
    )
  )

# ------------------------------------------------------------
# 16) Convert EV and APEV to USD
# ------------------------------------------------------------

municipal_economic_year <- municipal_economic_year_brl %>%
  left_join(exchange_rates, by = "year") %>%
  mutate(
    EV_usd = (EV_brl_thousand * 1000) / brl_per_usd,
    APEV_usd = (APEV_brl_thousand * 1000) / brl_per_usd
  )

# ------------------------------------------------------------
# 17) Mean EV, APEV and RV, 2020–2024
# ------------------------------------------------------------

municipal_economic_mean <- municipal_economic_year %>%
  group_by(municipality_code, municipality_name) %>%
  summarise(
    EV_usd_mean_2020_2024 =
      mean(EV_usd, na.rm = TRUE),
    APEV_usd_mean_2020_2024 =
      mean(APEV_usd, na.rm = TRUE),
    RV_percent_mean_2020_2024 =
      mean(RV_percent, na.rm = TRUE),
    EV_brl_thousand_mean_2020_2024 =
      mean(EV_brl_thousand, na.rm = TRUE),
    APEV_brl_thousand_mean_2020_2024 =
      mean(APEV_brl_thousand, na.rm = TRUE),
    n_crops_total_economic_mean_2020_2024 =
      mean(n_crops_total_economic, na.rm = TRUE),
    n_main_pollination_crops_economic_mean_2020_2024 =
      mean(n_main_pollination_crops_economic, na.rm = TRUE),
    .groups = "drop"
  )

# Annual totals used in Results section 3.1.
econ_year_total <- municipal_economic_year %>%
  group_by(year) %>%
  summarise(
    EV_usd_total = sum(EV_usd, na.rm = TRUE),
    APEV_usd_total = sum(APEV_usd, na.rm = TRUE),
    RV_percent_total = ifelse(
      EV_usd_total > 0,
      APEV_usd_total / EV_usd_total * 100,
      NA_real_
    ),
    .groups = "drop"
  )

# ============================================================
# PART C — SPATIAL REDISTRIBUTION USING A_gym
# ============================================================

# ------------------------------------------------------------
# 18) Agricultural and native area by municipality
# A_gym = agricultural area of municipality m inside grid g
# ------------------------------------------------------------

municipal_area <- grid_municipality_area %>%
  group_by(municipality_code) %>%
  summarise(
    agricultural_area_municipality_ha =
      sum(agricultural_area_grid_municipality_ha, na.rm = TRUE),
    native_area_municipality_ha =
      sum(native_area_grid_municipality_ha, na.rm = TRUE),
    .groups = "drop"
  )

# ------------------------------------------------------------
# 19) Redistribute mean PD, EV and APEV to grid × municipality
# PD_gm = PD_m * A_gm / sum_g(A_gm)
# EV_gm and APEV_gm follow the same dasymetric allocation.
# ------------------------------------------------------------

grid_municipality_allocated <- grid_municipality_area %>%
  left_join(municipal_area, by = "municipality_code") %>%
  left_join(
    municipal_demand_mean %>%
      select(
        municipality_code,
        production_main_total_mean_2020_2024,
        PD_mean_2020_2024,
        n_main_crops_mean_2020_2024
      ),
    by = "municipality_code"
  ) %>%
  left_join(
    municipal_economic_mean %>%
      select(
        municipality_code,
        EV_usd_mean_2020_2024,
        APEV_usd_mean_2020_2024,
        RV_percent_mean_2020_2024
      ),
    by = "municipality_code"
  ) %>%
  mutate(
    agricultural_area_share_municipality = ifelse(
      agricultural_area_municipality_ha > 0,
      agricultural_area_grid_municipality_ha / agricultural_area_municipality_ha,
      0
    ),
    PD_gym_mean_2020_2024 =
      PD_mean_2020_2024 * agricultural_area_share_municipality,
    production_main_gym_mean_2020_2024 =
      production_main_total_mean_2020_2024 * agricultural_area_share_municipality,
    EV_usd_gym_mean_2020_2024 =
      EV_usd_mean_2020_2024 * agricultural_area_share_municipality,
    APEV_usd_gym_mean_2020_2024 =
      APEV_usd_mean_2020_2024 * agricultural_area_share_municipality
  ) %>%
  mutate(
    across(
      c(
        PD_gym_mean_2020_2024,
        production_main_gym_mean_2020_2024,
        EV_usd_gym_mean_2020_2024,
        APEV_usd_gym_mean_2020_2024
      ),
      ~ tidyr::replace_na(.x, 0)
    )
  )

# ------------------------------------------------------------
# 20) Check whether municipal demand was preserved
# ------------------------------------------------------------

redistribution_check <- grid_municipality_allocated %>%
  group_by(municipality_code) %>%
  summarise(
    PD_municipal_original =
      first(tidyr::replace_na(PD_mean_2020_2024, 0)),
    PD_redistributed =
      sum(PD_gym_mean_2020_2024, na.rm = TRUE),
    agricultural_area_municipality_ha =
      first(agricultural_area_municipality_ha),
    difference =
      PD_municipal_original - PD_redistributed,
    .groups = "drop"
  )

redistribution_summary <- redistribution_check %>%
  summarise(
    PD_original_total =
      sum(PD_municipal_original, na.rm = TRUE),
    PD_redistributed_total =
      sum(PD_redistributed, na.rm = TRUE),
    difference_total =
      PD_original_total - PD_redistributed_total,
    percent_lost = ifelse(
      PD_original_total > 0,
      difference_total / PD_original_total * 100,
      NA_real_
    )
  )

# ============================================================
# PART D — GRID-LEVEL DEMAND, ECONOMIC VALUE AND SUPPLY
# ============================================================

# ------------------------------------------------------------
# 21) Aggregate allocated values by grid
# ------------------------------------------------------------

grid_attributes <- grid_municipality_allocated %>%
  group_by(grid_id) %>%
  summarise(
    intersection_area_total_ha =
      sum(intersection_area_ha, na.rm = TRUE),
    agricultural_area_ha =
      sum(agricultural_area_grid_municipality_ha, na.rm = TRUE),
    native_vegetation_area_ha =
      sum(native_area_grid_municipality_ha, na.rm = TRUE),
    PD_grid_mean_2020_2024 =
      sum(PD_gym_mean_2020_2024, na.rm = TRUE),
    production_main_grid_mean_2020_2024 =
      sum(production_main_gym_mean_2020_2024, na.rm = TRUE),
    EV_usd_grid_mean_2020_2024 =
      sum(EV_usd_gym_mean_2020_2024, na.rm = TRUE),
    APEV_usd_grid_mean_2020_2024 =
      sum(APEV_usd_gym_mean_2020_2024, na.rm = TRUE),
    n_municipal_intersections =
      n_distinct(municipality_code),
    .groups = "drop"
  ) %>%
  mutate(
    RV_percent_grid_mean_2020_2024 = ifelse(
      EV_usd_grid_mean_2020_2024 > 0,
      APEV_usd_grid_mean_2020_2024 /
        EV_usd_grid_mean_2020_2024 * 100,
      NA_real_
    )
  )

# ------------------------------------------------------------
# 22) Join attributes to grid geometry
# ------------------------------------------------------------

grid_final <- grid %>%
  left_join(grid_attributes, by = "grid_id") %>%
  mutate(
    grid_area_ha = as.numeric(sf::st_area(.)) / 10000,
    agricultural_area_ha = tidyr::replace_na(agricultural_area_ha, 0),
    native_vegetation_area_ha = tidyr::replace_na(native_vegetation_area_ha, 0),
    PD_grid_mean_2020_2024 =
      tidyr::replace_na(PD_grid_mean_2020_2024, 0),
    production_main_grid_mean_2020_2024 =
      tidyr::replace_na(production_main_grid_mean_2020_2024, 0),
    EV_usd_grid_mean_2020_2024 =
      tidyr::replace_na(EV_usd_grid_mean_2020_2024, 0),
    APEV_usd_grid_mean_2020_2024 =
      tidyr::replace_na(APEV_usd_grid_mean_2020_2024, 0),
    agricultural_proportion = agricultural_area_ha / grid_area_ha,
    native_vegetation_proportion = native_vegetation_area_ha / grid_area_ha,
    PD_density_grid = PD_grid_mean_2020_2024 / grid_area_ha,
    PD_density_agriculture = ifelse(
      agricultural_area_ha > 0,
      PD_grid_mean_2020_2024 / agricultural_area_ha,
      0
    ),
    has_agriculture = agricultural_area_ha > 1,
    has_pollination_demand = PD_grid_mean_2020_2024 > 0
  )

# Keep only grid cells with agricultural land for demand-supply analyses.
grid_agri <- grid_final %>%
  filter(has_agriculture)

# ============================================================
# PART E — POTENTIAL SUPPLY AND DEMAND–SUPPLY MISMATCH
# ============================================================

# ------------------------------------------------------------
# 23) Rescaling function
# ------------------------------------------------------------

rescale01 <- function(x) {
  rng <- range(x, na.rm = TRUE)

  if (
    is.infinite(rng[1]) ||
      is.infinite(rng[2]) ||
      diff(rng) == 0
  ) {
    return(rep(0, length(x)))
  }

  (x - rng[1]) / (rng[2] - rng[1])
}

# ------------------------------------------------------------
# 24) Calculate potential supply and mismatch
# Potential supply = proportion of native vegetation per grid cell
# Demand = log1p(PD), rescaled to 0–1
# Risk_g = Demand_std * (1 - Supply_std)
# Mismatch_g = Demand_std - Supply_std
# ------------------------------------------------------------

grid_mismatch <- grid_agri %>%
  mutate(
    habitat_agriculture_total_ha = agricultural_area_ha + native_vegetation_area_ha,
    native_supply_proportion = native_vegetation_proportion,
    habitat_agriculture_supply = ifelse(
      habitat_agriculture_total_ha > 0,
      native_vegetation_area_ha / habitat_agriculture_total_ha,
      NA_real_
    ),
    native_area_supply_log = log1p(native_vegetation_area_ha),
    demand_std = rescale01(log1p(PD_grid_mean_2020_2024)),
    supply_std = rescale01(native_supply_proportion),
    habitat_agriculture_supply_std = rescale01(habitat_agriculture_supply),
    supply_std_area = rescale01(native_area_supply_log),
    risk_deficit = demand_std * (1 - supply_std),
    mismatch = demand_std - supply_std,
    risk_deficit_habitat_agriculture = demand_std * (1 - habitat_agriculture_supply_std),
    risk_deficit_area = demand_std * (1 - supply_std_area)
  )

# ------------------------------------------------------------
# 25) Risk classes and mismatch categories
# ------------------------------------------------------------

risk_breaks <- quantile(
  grid_mismatch$risk_deficit,
  probs = c(0, 0.25, 0.5, 0.75, 1),
  na.rm = TRUE
)

q_high_demand <- quantile(
  grid_mismatch$demand_std,
  0.75,
  na.rm = TRUE
)

q_low_supply <- quantile(
  grid_mismatch$supply_std,
  0.25,
  na.rm = TRUE
)

q_high_supply <- quantile(
  grid_mismatch$supply_std,
  0.75,
  na.rm = TRUE
)

grid_mismatch <- grid_mismatch %>%
  mutate(
    risk_class = case_when(
      risk_deficit <= risk_breaks[2] ~ "low",
      risk_deficit <= risk_breaks[3] ~ "moderate",
      risk_deficit <= risk_breaks[4] ~ "high",
      TRUE ~ "very high"
    ),
    risk_class = factor(
      risk_class,
      levels = c("low", "moderate", "high", "very high")
    ),
    mismatch_category = case_when(
      demand_std >= q_high_demand &
        supply_std <= q_low_supply ~
        "high demand + low supply",
      demand_std >= q_high_demand &
        supply_std > q_low_supply ~
        "high demand + moderate/high supply",
      demand_std < q_high_demand &
        supply_std <= q_low_supply ~
        "low/moderate demand + low supply",
      demand_std < q_high_demand &
        supply_std >= q_high_supply ~
        "low/moderate demand + high supply",
      TRUE ~ "intermediate condition"
    ),
    mismatch_category = factor(
      mismatch_category,
      levels = c(
        "high demand + low supply",
        "high demand + moderate/high supply",
        "low/moderate demand + low supply",
        "low/moderate demand + high supply",
        "intermediate condition"
      )
    )
  )

# ------------------------------------------------------------
# 26) Add dominant state to each grid cell
# ------------------------------------------------------------

grid_state <- grid_municipality_area %>%
  group_by(grid_id, state_abbrev) %>%
  summarise(
    state_intersection_area_ha =
      sum(intersection_area_ha, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  group_by(grid_id) %>%
  slice_max(
    state_intersection_area_ha,
    n = 1,
    with_ties = FALSE
  ) %>%
  ungroup() %>%
  select(grid_id, state_abbrev)

grid_mismatch <- grid_mismatch %>%
  left_join(grid_state, by = "grid_id")

# ============================================================
# PART F — SUMMARIES, HOTSPOTS AND CONCENTRATION
# ============================================================

# ------------------------------------------------------------
# 27) General summary
# ------------------------------------------------------------

summary_general <- grid_mismatch %>%
  sf::st_drop_geometry() %>%
  summarise(
    n_grid_cells_with_agriculture = n(),
    agricultural_area_ha =
      sum(agricultural_area_ha, na.rm = TRUE),
    native_vegetation_area_ha =
      sum(native_vegetation_area_ha, na.rm = TRUE),
    PD_total_mean_2020_2024 =
      sum(PD_grid_mean_2020_2024, na.rm = TRUE),
    EV_usd_total_mean_2020_2024 =
      sum(EV_usd_grid_mean_2020_2024, na.rm = TRUE),
    APEV_usd_total_mean_2020_2024 =
      sum(APEV_usd_grid_mean_2020_2024, na.rm = TRUE),
    RV_percent_total = ifelse(
      EV_usd_total_mean_2020_2024 > 0,
      APEV_usd_total_mean_2020_2024 /
        EV_usd_total_mean_2020_2024 * 100,
      NA_real_
    ),
    mean_RV_percent_grid =
      mean(RV_percent_grid_mean_2020_2024, na.rm = TRUE),
    mean_native_vegetation_proportion =
      mean(native_vegetation_proportion, na.rm = TRUE),
    median_native_vegetation_proportion =
      median(native_vegetation_proportion, na.rm = TRUE),
    sd_native_vegetation_proportion =
      sd(native_vegetation_proportion, na.rm = TRUE),
    mean_risk_deficit =
      mean(risk_deficit, na.rm = TRUE),
    median_risk_deficit =
      median(risk_deficit, na.rm = TRUE),
    mean_mismatch =
      mean(mismatch, na.rm = TRUE),
    median_mismatch =
      median(mismatch, na.rm = TRUE)
  )

# ------------------------------------------------------------
# 28) Summary by risk class
# ------------------------------------------------------------

summary_risk_class <- grid_mismatch %>%
  sf::st_drop_geometry() %>%
  group_by(risk_class) %>%
  summarise(
    n_grid_cells = n(),
    PD_total_mean_2020_2024 =
      sum(PD_grid_mean_2020_2024, na.rm = TRUE),
    agricultural_area_ha =
      sum(agricultural_area_ha, na.rm = TRUE),
    native_vegetation_area_ha =
      sum(native_vegetation_area_ha, na.rm = TRUE),
    EV_usd_total_mean_2020_2024 =
      sum(EV_usd_grid_mean_2020_2024, na.rm = TRUE),
    APEV_usd_total_mean_2020_2024 =
      sum(APEV_usd_grid_mean_2020_2024, na.rm = TRUE),
    RV_percent_total = ifelse(
      EV_usd_total_mean_2020_2024 > 0,
      APEV_usd_total_mean_2020_2024 /
        EV_usd_total_mean_2020_2024 * 100,
      NA_real_
    ),
    mean_native_vegetation_proportion =
      mean(native_vegetation_proportion, na.rm = TRUE),
    mean_risk_deficit =
      mean(risk_deficit, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    percent_grid_cells =
      n_grid_cells / sum(n_grid_cells, na.rm = TRUE) * 100,
    percent_PD =
      PD_total_mean_2020_2024 /
      sum(PD_total_mean_2020_2024, na.rm = TRUE) * 100,
    percent_APEV =
      APEV_usd_total_mean_2020_2024 /
      sum(APEV_usd_total_mean_2020_2024, na.rm = TRUE) * 100
  )

# ------------------------------------------------------------
# 29) Summary by mismatch category
# ------------------------------------------------------------

summary_mismatch_category <- grid_mismatch %>%
  sf::st_drop_geometry() %>%
  group_by(mismatch_category) %>%
  summarise(
    n_grid_cells = n(),
    PD_total_mean_2020_2024 =
      sum(PD_grid_mean_2020_2024, na.rm = TRUE),
    agricultural_area_ha =
      sum(agricultural_area_ha, na.rm = TRUE),
    native_vegetation_area_ha =
      sum(native_vegetation_area_ha, na.rm = TRUE),
    EV_usd_total_mean_2020_2024 =
      sum(EV_usd_grid_mean_2020_2024, na.rm = TRUE),
    APEV_usd_total_mean_2020_2024 =
      sum(APEV_usd_grid_mean_2020_2024, na.rm = TRUE),
    RV_percent_total = ifelse(
      EV_usd_total_mean_2020_2024 > 0,
      APEV_usd_total_mean_2020_2024 /
        EV_usd_total_mean_2020_2024 * 100,
      NA_real_
    ),
    mean_risk_deficit =
      mean(risk_deficit, na.rm = TRUE),
    mean_native_vegetation_proportion =
      mean(native_vegetation_proportion, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    percent_grid_cells =
      n_grid_cells / sum(n_grid_cells, na.rm = TRUE) * 100,
    percent_PD =
      PD_total_mean_2020_2024 /
      sum(PD_total_mean_2020_2024, na.rm = TRUE) * 100,
    percent_APEV =
      APEV_usd_total_mean_2020_2024 /
      sum(APEV_usd_total_mean_2020_2024, na.rm = TRUE) * 100
  )

# ------------------------------------------------------------
# 30) Critical hotspots: high demand + low supply
# ------------------------------------------------------------

critical_hotspots <- grid_mismatch %>%
  filter(mismatch_category == "high demand + low supply") %>%
  sf::st_drop_geometry() %>%
  arrange(desc(risk_deficit))

critical_hotspots_by_state <- critical_hotspots %>%
  group_by(state_abbrev) %>%
  summarise(
    n_grid_cells = n(),
    PD_total_mean_2020_2024 =
      sum(PD_grid_mean_2020_2024, na.rm = TRUE),
    agricultural_area_ha =
      sum(agricultural_area_ha, na.rm = TRUE),
    native_vegetation_area_ha =
      sum(native_vegetation_area_ha, na.rm = TRUE),
    EV_usd_total_mean_2020_2024 =
      sum(EV_usd_grid_mean_2020_2024, na.rm = TRUE),
    APEV_usd_total_mean_2020_2024 =
      sum(APEV_usd_grid_mean_2020_2024, na.rm = TRUE),
    RV_percent_total = ifelse(
      EV_usd_total_mean_2020_2024 > 0,
      APEV_usd_total_mean_2020_2024 /
        EV_usd_total_mean_2020_2024 * 100,
      NA_real_
    ),
    mean_risk_deficit =
      mean(risk_deficit, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    percent_grid_cells = ifelse(
      sum(n_grid_cells, na.rm = TRUE) > 0,
      n_grid_cells / sum(n_grid_cells, na.rm = TRUE) * 100,
      NA_real_
    ),
    percent_PD = ifelse(
      sum(PD_total_mean_2020_2024, na.rm = TRUE) > 0,
      PD_total_mean_2020_2024 /
        sum(PD_total_mean_2020_2024, na.rm = TRUE) * 100,
      NA_real_
    ),
    native_vegetation_proportion =
      native_vegetation_area_ha /
      (agricultural_area_ha + native_vegetation_area_ha)
  ) %>%
  arrange(desc(PD_total_mean_2020_2024))

# ------------------------------------------------------------
# 31) Hotspot concentration by risk ranking
# ------------------------------------------------------------
# Supports Results section 3.3:
# grid cells are ranked by pollination deficit risk, and cumulative
# proportions of total PD, APEV and EV are calculated.

risk_ranked_cells <- grid_mismatch %>%
  sf::st_drop_geometry() %>%
  arrange(desc(risk_deficit)) %>%
  mutate(
    risk_rank = row_number(),
    top_fraction_cells = risk_rank / n(),
    top_percent_cells = top_fraction_cells * 100,
    cumulative_PD = cumsum(PD_grid_mean_2020_2024),
    cumulative_APEV_usd = cumsum(APEV_usd_grid_mean_2020_2024),
    cumulative_EV_usd = cumsum(EV_usd_grid_mean_2020_2024),
    cumulative_PD_percent =
      cumulative_PD /
      sum(PD_grid_mean_2020_2024, na.rm = TRUE) * 100,
    cumulative_APEV_percent =
      cumulative_APEV_usd /
      sum(APEV_usd_grid_mean_2020_2024, na.rm = TRUE) * 100,
    cumulative_EV_percent =
      cumulative_EV_usd /
      sum(EV_usd_grid_mean_2020_2024, na.rm = TRUE) * 100
  )

concentration_thresholds <- risk_ranked_cells %>%
  summarise(
    PD_top_1_percent =
      cumulative_PD_percent[which.min(abs(top_percent_cells - 1))],
    PD_top_5_percent =
      cumulative_PD_percent[which.min(abs(top_percent_cells - 5))],
    PD_top_10_percent =
      cumulative_PD_percent[which.min(abs(top_percent_cells - 10))],
    PD_top_25_percent =
      cumulative_PD_percent[which.min(abs(top_percent_cells - 25))],
    APEV_top_1_percent =
      cumulative_APEV_percent[which.min(abs(top_percent_cells - 1))],
    APEV_top_5_percent =
      cumulative_APEV_percent[which.min(abs(top_percent_cells - 5))],
    APEV_top_10_percent =
      cumulative_APEV_percent[which.min(abs(top_percent_cells - 10))],
    APEV_top_25_percent =
      cumulative_APEV_percent[which.min(abs(top_percent_cells - 25))],
    EV_top_1_percent =
      cumulative_EV_percent[which.min(abs(top_percent_cells - 1))],
    EV_top_5_percent =
      cumulative_EV_percent[which.min(abs(top_percent_cells - 5))],
    EV_top_10_percent =
      cumulative_EV_percent[which.min(abs(top_percent_cells - 10))],
    EV_top_25_percent =
      cumulative_EV_percent[which.min(abs(top_percent_cells - 25))]
  )

# ------------------------------------------------------------
# 32) Save main spatial and summary outputs before crop metrics
# ------------------------------------------------------------

sf::st_write(
  grid_mismatch,
  file.path(output_dir, "grid_pollination_mismatch_mean_2020_2024.gpkg"),
  delete_dsn = TRUE,
  quiet = TRUE
)

write_csv(
  grid_mismatch %>% sf::st_drop_geometry(),
  file.path(output_dir, "grid_pollination_mismatch_mean_2020_2024.csv")
)

write_csv(
  summary_general,
  file.path(output_dir, "summary_general_mean_2020_2024.csv")
)

write_csv(
  summary_risk_class,
  file.path(output_dir, "summary_risk_class_mean_2020_2024.csv")
)

write_csv(
  summary_mismatch_category,
  file.path(output_dir, "summary_mismatch_category_mean_2020_2024.csv")
)

write_csv(
  critical_hotspots,
  file.path(output_dir, "critical_hotspots_mean_2020_2024.csv")
)

write_csv(
  critical_hotspots_by_state,
  file.path(output_dir, "critical_hotspots_by_state_mean_2020_2024.csv")
)

# ============================================================
# PART G — CROP-LEVEL ANALYSES
# ============================================================

# ------------------------------------------------------------
# 33) Crop-level pollination demand
# ------------------------------------------------------------

crop_pd_year <- pam %>%
  filter(
    variable_name_clean == "quantidade produzida",
    is_main_pollination_crop
  ) %>%
  mutate(
    crop_production = value,
    crop_PD = crop_production * dependence_score
  ) %>%
  group_by(
    year,
    municipality_code,
    municipality_name,
    crop_code,
    crop_name,
    pollination_dependence
  ) %>%
  summarise(
    crop_production =
      sum(crop_production, na.rm = TRUE),
    crop_PD =
      sum(crop_PD, na.rm = TRUE),
    .groups = "drop"
  )

crop_pd_mean <- crop_pd_year %>%
  group_by(
    municipality_code,
    municipality_name,
    crop_code,
    crop_name,
    pollination_dependence
  ) %>%
  summarise(
    crop_production_mean_2020_2024 =
      mean(crop_production, na.rm = TRUE),
    crop_PD_mean_2020_2024 =
      mean(crop_PD, na.rm = TRUE),
    .groups = "drop"
  )

# ------------------------------------------------------------
# 34) Pollinator-dependent crop diversity by municipality
# Shannon index using crop PD proportions
# ------------------------------------------------------------

crop_diversity_municipality <- crop_pd_mean %>%
  group_by(municipality_code, municipality_name) %>%
  mutate(
    total_PD_municipality =
      sum(crop_PD_mean_2020_2024, na.rm = TRUE),
    p_crop = ifelse(
      total_PD_municipality > 0,
      crop_PD_mean_2020_2024 / total_PD_municipality,
      NA_real_
    )
  ) %>%
  summarise(
    shannon_PD_crops =
      -sum(p_crop * log(p_crop), na.rm = TRUE),
    n_main_pollination_crops =
      n_distinct(crop_code[crop_PD_mean_2020_2024 > 0]),
    total_PD_municipality =
      first(total_PD_municipality),
    .groups = "drop"
  )

# ------------------------------------------------------------
# 35) Dominant crop by municipality
# ------------------------------------------------------------

dominant_crop_municipality <- crop_pd_mean %>%
  group_by(municipality_code, municipality_name) %>%
  mutate(
    total_PD_municipality =
      sum(crop_PD_mean_2020_2024, na.rm = TRUE),
    crop_PD_percent = ifelse(
      total_PD_municipality > 0,
      crop_PD_mean_2020_2024 / total_PD_municipality * 100,
      NA_real_
    )
  ) %>%
  arrange(desc(crop_PD_mean_2020_2024), .by_group = TRUE) %>%
  slice(1) %>%
  ungroup() %>%
  transmute(
    municipality_code,
    municipality_name,
    dominant_crop_municipality = crop_name,
    dominant_crop_code_municipality = crop_code,
    dominant_crop_dependence_municipality = pollination_dependence,
    dominant_crop_PD_municipality = crop_PD_mean_2020_2024,
    dominant_crop_percent_municipality = crop_PD_percent,
    total_PD_municipality
  )

n_crops_municipality <- crop_pd_mean %>%
  filter(crop_PD_mean_2020_2024 > 0) %>%
  group_by(municipality_code, municipality_name) %>%
  summarise(
    n_main_pollination_crops = n_distinct(crop_code),
    .groups = "drop"
  )

dominant_crop_municipality <- dominant_crop_municipality %>%
  left_join(
    n_crops_municipality,
    by = c("municipality_code", "municipality_name")
  )

# ------------------------------------------------------------
# 36) Dominant municipality in each grid
# ------------------------------------------------------------

dominant_municipality_grid <- grid_municipality_allocated %>%
  group_by(grid_id, municipality_code) %>%
  summarise(
    municipality_grid_intersection_area_ha =
      sum(intersection_area_ha, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  group_by(grid_id) %>%
  slice_max(
    municipality_grid_intersection_area_ha,
    n = 1,
    with_ties = FALSE
  ) %>%
  ungroup()

# ------------------------------------------------------------
# 37) Add municipal crop diversity and municipal dominant crop
# ------------------------------------------------------------

grid_mismatch <- grid_mismatch %>%
  select(
    -any_of(c(
      "dominant_municipality_code",
      "shannon_PD_crops",
      "n_main_pollination_crops",
      "dominant_crop_municipality",
      "dominant_crop_dependence_municipality",
      "dominant_crop_PD_municipality",
      "dominant_crop_percent_municipality"
    ))
  ) %>%
  left_join(
    dominant_municipality_grid %>%
      select(
        grid_id,
        dominant_municipality_code = municipality_code
      ),
    by = "grid_id"
  ) %>%
  left_join(
    crop_diversity_municipality %>%
      select(
        dominant_municipality_code = municipality_code,
        shannon_PD_crops,
        n_main_pollination_crops
      ),
    by = "dominant_municipality_code"
  ) %>%
  left_join(
    dominant_crop_municipality %>%
      select(
        dominant_municipality_code = municipality_code,
        dominant_crop_municipality,
        dominant_crop_dependence_municipality,
        dominant_crop_PD_municipality,
        dominant_crop_percent_municipality
      ),
    by = "dominant_municipality_code"
  )

# ------------------------------------------------------------
# 38) Allocate crop-level municipal PD to grid cells
# Same dasymetric allocation procedure based on agricultural area
# ------------------------------------------------------------

crop_grid_allocated <- grid_municipality_area %>%
  left_join(municipal_area, by = "municipality_code") %>%
  left_join(crop_pd_mean, by = "municipality_code") %>%
  mutate(
    agricultural_area_share_municipality = ifelse(
      agricultural_area_municipality_ha > 0,
      agricultural_area_grid_municipality_ha / agricultural_area_municipality_ha,
      0
    ),
    crop_PD_grid =
      crop_PD_mean_2020_2024 * agricultural_area_share_municipality,
    crop_PD_grid =
      tidyr::replace_na(crop_PD_grid, 0)
  )

# ------------------------------------------------------------
# 39) Dominant crop directly by grid
# Dominant crop = largest share of total grid-level PD
# ------------------------------------------------------------

dominant_crop_grid <- crop_grid_allocated %>%
  filter(!is.na(crop_code)) %>%
  group_by(
    grid_id,
    crop_code,
    crop_name,
    pollination_dependence
  ) %>%
  summarise(
    crop_PD_grid =
      sum(crop_PD_grid, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  group_by(grid_id) %>%
  mutate(
    total_PD_grid_from_crops =
      sum(crop_PD_grid, na.rm = TRUE),
    crop_PD_percent_grid = ifelse(
      total_PD_grid_from_crops > 0,
      crop_PD_grid / total_PD_grid_from_crops * 100,
      NA_real_
    )
  ) %>%
  filter(total_PD_grid_from_crops > 0) %>%
  arrange(desc(crop_PD_grid), .by_group = TRUE) %>%
  slice(1) %>%
  ungroup() %>%
  transmute(
    grid_id = as.character(grid_id),
    dominant_crop_grid = crop_name,
    dominant_crop_code_grid = crop_code,
    dominant_crop_dependence_grid = pollination_dependence,
    dominant_crop_PD_grid = crop_PD_grid,
    dominant_crop_percent_grid = crop_PD_percent_grid,
    total_PD_grid_from_crops
  )

# ------------------------------------------------------------
# 40) Add grid-level dominant crop safely
# ------------------------------------------------------------

grid_mismatch <- grid_mismatch %>%
  select(
    -matches("^dominant_crop_grid"),
    -matches("^dominant_crop_code_grid"),
    -matches("^dominant_crop_dependence_grid"),
    -matches("^dominant_crop_PD_grid"),
    -matches("^dominant_crop_percent_grid"),
    -matches("^total_PD_grid_from_crops")
  ) %>%
  mutate(grid_id = as.character(grid_id)) %>%
  left_join(
    dominant_crop_grid,
    by = "grid_id"
  )

# ------------------------------------------------------------
# 41) Summary of dominant crops in critical hotspots
# ------------------------------------------------------------

dominant_crop_hotspots_summary <- grid_mismatch %>%
  sf::st_drop_geometry() %>%
  filter(mismatch_category == "high demand + low supply") %>%
  group_by(dominant_crop_grid) %>%
  summarise(
    n_grid_cells = n(),
    PD_total =
      sum(PD_grid_mean_2020_2024, na.rm = TRUE),
    EV_usd_total =
      sum(EV_usd_grid_mean_2020_2024, na.rm = TRUE),
    APEV_usd_total =
      sum(APEV_usd_grid_mean_2020_2024, na.rm = TRUE),
    mean_dominant_crop_percent =
      mean(dominant_crop_percent_grid, na.rm = TRUE),
    mean_risk_deficit =
      mean(risk_deficit, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(desc(PD_total))


# ============================================================
# PART H — CORRELATION ANALYSIS
# ============================================================

# ------------------------------------------------------------
# 42) Spearman and Pearson correlations among grid-level metrics
# ------------------------------------------------------------

metrics_correlation <- grid_mismatch %>%
  sf::st_drop_geometry() %>%
  select(
    PD_grid_mean_2020_2024,
    APEV_usd_grid_mean_2020_2024,
    EV_usd_grid_mean_2020_2024,
    RV_percent_grid_mean_2020_2024,
    agricultural_area_ha,
    native_vegetation_area_ha,
    native_vegetation_proportion,
    risk_deficit,
    mismatch,
    shannon_PD_crops,
    n_main_pollination_crops
  )

correlation_matrix_spearman <- cor(
  metrics_correlation,
  use = "pairwise.complete.obs",
  method = "spearman"
)

correlation_matrix_pearson <- cor(
  metrics_correlation,
  use = "pairwise.complete.obs",
  method = "pearson"
)

# ============================================================
# PART I — SAVE UPDATED FINAL GRID OBJECT WITH CROP METRICS
# ============================================================

sf::st_write(
  grid_mismatch,
  file.path(
    output_dir,
    "grid_pollination_mismatch_crop_metrics_mean_2020_2024.gpkg"
  ),
  delete_dsn = TRUE,
  quiet = TRUE
)

write_csv(
  grid_mismatch %>% sf::st_drop_geometry(),
  file.path(
    output_dir,
    "grid_pollination_mismatch_crop_metrics_mean_2020_2024.csv"
  )
)


# ============================================================
# PART K — TABLES FOR THE ARTICLE
# ============================================================

# ------------------------------------------------------------
# 55) Table 1 — General summary
# ------------------------------------------------------------

table1_summary <- summary_general %>%
  mutate(
    agricultural_area_mha = agricultural_area_ha / 1e6,
    native_vegetation_area_mha = native_vegetation_area_ha / 1e6,
    EV_usd_billion = EV_usd_total_mean_2020_2024 / 1e9,
    APEV_usd_billion = APEV_usd_total_mean_2020_2024 / 1e9
  ) %>%
  select(
    n_grid_cells_with_agriculture,
    agricultural_area_mha,
    native_vegetation_area_mha,
    PD_total_mean_2020_2024,
    EV_usd_billion,
    APEV_usd_billion,
    RV_percent_total,
    mean_RV_percent_grid,
    mean_native_vegetation_proportion,
    median_native_vegetation_proportion,
    sd_native_vegetation_proportion,
    mean_risk_deficit,
    median_risk_deficit,
    mean_mismatch,
    median_mismatch
  )

write_csv(
  table1_summary,
  file.path(tab_dir, "Table_1_summary_general.csv")
)

# ------------------------------------------------------------
# 57) Table S2 — Dominant crops in critical hotspots
# Table S1 is reserved above for the state-standardized hotspot table.
# ------------------------------------------------------------

table_dominant_crops_hotspots <- dominant_crop_hotspots_summary %>%
  mutate(
    PD_million = PD_total / 1e6,
    EV_usd_billion = EV_usd_total / 1e9,
    APEV_usd_billion = APEV_usd_total / 1e9
  ) %>%
  select(
    dominant_crop_grid,
    n_grid_cells,
    PD_million,
    EV_usd_billion,
    APEV_usd_billion,
    mean_dominant_crop_percent,
    mean_risk_deficit
  )

# ------------------------------------------------------------
# 58) Unique crops included in the main analysis
# ------------------------------------------------------------

unique_crops_main <- pam_quantity_main %>%
  distinct(
    crop_code,
    crop_name,
    pollination_dependence,
    dependence_score,
    classification_reference
  ) %>%
  arrange(crop_name)

# ------------------------------------------------------------
# 59) Total production by crop across all years and municipalities
# Only essential, high and modest dependence
# ------------------------------------------------------------

crop_quantity_totals <- pam_quantity_main %>%
  group_by(
    crop_code,
    crop_name,
    pollination_dependence,
    dependence_score,
    classification_reference
  ) %>%
  summarise(
    n_rows = n(),
    n_municipalities = n_distinct(municipality_code),
    n_years = n_distinct(year),
    total_quantity_2020_2024 =
      sum(value, na.rm = TRUE),
    mean_annual_quantity =
      total_quantity_2020_2024 / n_years,
    median_municipality_year_quantity =
      median(value, na.rm = TRUE),
    n_missing = sum(is.na(value)),
    .groups = "drop"
  ) %>%
  arrange(desc(total_quantity_2020_2024))


# ============================================================
# PART M — FINAL INSPECTION
# ============================================================

cat("\nMain dependence levels used in PD and APEV calculations:\n")
print(main_dependence_levels)

cat("\nDependence classes included in pam_quantity_main:\n")
print(
  pam_quantity_main %>%
    count(pollination_dependence, dependence_score)
)

print(summary_general)
print(summary_risk_class)
print(summary_mismatch_category)
print(critical_hotspots_by_state)
print(redistribution_summary)
print(econ_year_total)
print(concentration_thresholds)
print(dominant_crop_hotspots_summary)
print(correlation_matrix_spearman)

# End of script.
